# Generated by Django 4.2.4 on 2023-09-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicpick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
