# Generated by Django 4.2.4 on 2023-09-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpick', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=1900),
        ),
    ]
