# Generated by Django 4.2.4 on 2023-09-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpick', '0004_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.ManyToManyField(through='basicpick.MovieGenre', to='basicpick.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
