# Generated by Django 4.2.4 on 2023-09-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpick', '0005_movie_movie_genre_alter_movie_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='seen',
            new_name='rewatch',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_watched',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
