# Generated by Django 4.2.4 on 2023-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpick', '0006_rename_seen_movie_rewatch_movie_date_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_watched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
